---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/index.json
  label: Homepage
- type: document
  path: content/about.json
  label: About
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/list/*"
  new_doc_ext: json
  templates:
  - article
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/list/*"
  new_doc_ext: json
  templates:
  - event
- type: directory
  path: content/people
  label: People
  create: all
  match: "**/list/*"
  new_doc_ext: json
  templates:
  - person
- type: directory
  path: content/places
  label: Places
  create: all
  match: "**/list/*"
  new_doc_ext: json
  templates:
  - advertisement
- type: directory
  path: content/product
  label: Products
  create: all
  match: "**/list/*"
  new_doc_ext: json
  templates:
  - product
- type: directory
  path: content/recipes
  label: Recipes
  create: all
  match: "**/list/*"
  new_doc_ext: json
  templates:
  - recipe
- type: heading
  label: Configuration
- type: document
  path: content/branding.json
  label: _branding
- type: document
  path: content/navigation.json
  label: _navigation
- type: document
  path: content/footer.json
  label: _footer
- type: document
  path: content/analytics.json
  label: _analytics
- type: document
  path: content/sitemap.json
  label: _sitemap
- type: document
  path: content/robots.json
  label: _robots
- type: document
  path: content/comments.json
  label: _comments
- type: document
  path: content/feed.json
  label: _feed
- type: document
  path: content/socialmedia.json
  label: _socialmedia
  match: "**/*"
upload_dir: assets/uploads
public_path: "/content/example/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
