---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/sitemap.json
  label: sitemap.xml
  match: "**/*"
- type: document
  path: content/about.json
  label: About
  match: "**/*"
- type: document
  path: content/robots.json
  label: robots.txt
- type: directory
  path: content/advertisements
  label: Advertisements
  create: all
  match: "**/list/*"
  new_doc_ext: json
  templates:
  - advertisement
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/list/*"
  new_doc_ext: json
  templates:
  - recipe
  - article
- type: document
  path: content/index.json
  label: Homepage
upload_dir: assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
