---
label: Product
hide_body: true
fields:
- name: category
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: categories
      file: 
      path: 
  label: Category
